name: CI do dbt (Verificação Básica)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Verificar Código
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código (Checkout)
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dbt-postgres
      run: |
        pip install dbt-postgres

    - name: Criar Arquivo de Configuração (profiles.yml)
      run: |
        cd transformacoes_asaas
        echo "transformacoes_asaas:" > profiles.yml
        echo "  target: dev" >> profiles.yml
        echo "  outputs:" >> profiles.yml
        echo "    dev:" >> profiles.yml
        echo "      type: postgres" >> profiles.yml
        echo "      host: localhost" >> profiles.yml
        echo "      user: usuario_ci" >> profiles.yml
        echo "      password: senha_ci" >> profiles.yml
        echo "      port: 5432" >> profiles.yml
        echo "      dbname: banco_ci" >> profiles.yml
        echo "      schema: analytics" >> profiles.yml

    - name: Instalar Dependências
      run: |
        cd transformacoes_asaas
        # O ponto (.) diz ao dbt: "Use o profiles.yml que está nesta pasta aqui"
        dbt deps --profiles-dir .

    - name: Verificar Sintaxe (Parse)
      run: |
        cd transformacoes_asaas
        dbt parse --profiles-dir .