name: CI do dbt (Verificação Básica)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Verificar Instalação dbt
    runs-on: ubuntu-latest 

    steps:
    - name: Baixar código (Checkout)
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dbt-postgres
      run: |
        pip install dbt-postgres

    
    - name: Instalar Dependências do Projeto
      run: |
        cd transformacoes_asaas
        dbt deps


    - name: Verificar Sintaxe (Parse)
      run: |
        cd transformacoes_asaas
        dbt parse